#!/bin/bash
#SBATCH --job-name=fds_container_build
#SBATCH --output=fds_container_build_%j.out
#SBATCH --error=fds_container_build_%j.err
#SBATCH --time=48:00:00
#SBATCH --partition=normal
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --exclusive

set -euo pipefail

BASE_DIR="/beegfs/gopal/new/fds"
DEF_FILE="${BASE_DIR}/fds_build.def"
IMAGE="${BASE_DIR}/fds_image.sif"
ENV_FILE="${BASE_DIR}/host_mpi_env.sh"
UCX_INFO_FILE="${BASE_DIR}/host_openmpi_ucx.txt"
LOG_DIR="${BASE_DIR}/logs"
BUILD_LOG="${LOG_DIR}/fds-container-build.log"
ERROR_LOG="${LOG_DIR}/fds-container-errors.log"
APPTAINER_TMPDIR="${BASE_DIR}/apptainer_tmp"
APPTAINER_CACHEDIR="${BASE_DIR}/apptainer_cache"
NBUILD="${SLURM_CPUS_PER_TASK:-16}"

cd "$BASE_DIR"
mkdir -p "$LOG_DIR" "$APPTAINER_TMPDIR" "$APPTAINER_CACHEDIR"

export APPTAINER_TMPDIR APPTAINER_CACHEDIR
export APPTAINER_BUILD_CPUS="$NBUILD"

test -f "$DEF_FILE" || { echo "ERROR: missing $DEF_FILE"; exit 1; }

for v in FOAM_INST_DIR WM_PROJECT_DIR WM_THIRD_PARTY_DIR WM_OPTIONS WM_COMPILER \
    WM_MPLIB FOAM_MPI FDS_HOME FDS_BIN CC CXX FC F77 F90 CPATH \
    C_INCLUDE_PATH CPLUS_INCLUDE_PATH; do
    unset "$v" || true
done

module purge
module load 2023a
module load GCC/12.3.0
module load OpenMPI/4.1.5
module load CMake

module list 2>&1 || true

for cmd in gcc g++ gfortran mpicc mpicxx mpifort mpirun ompi_info apptainer; do
    command -v "$cmd" >/dev/null 2>&1 || { echo "ERROR: $cmd unavailable"; exit 10; }
done

case "$(gcc -dumpfullversion)" in
    12.3.0*) ;;
    *) echo "ERROR: GCC 12.3.0 not active"; exit 11 ;;
esac

case "$(mpirun --version | sed -n '1p')" in
    *4.1.5*) ;;
    *) echo "ERROR: OpenMPI 4.1.5 not active"; exit 12 ;;
esac

MPI_HOME="$(dirname "$(dirname "$(command -v mpirun)")")"
case "$MPI_HOME" in
    /beegfs/Tools/*OpenMPI/4.1.5-GCC-12.3.0) ;;
    *) echo "ERROR: unexpected MPI_HOME=$MPI_HOME"; exit 13 ;;
esac

ompi_info --param pml ucx --level 1 >"$UCX_INFO_FILE" 2>&1 || true
cat "$UCX_INFO_FILE"
grep -q "MCA pml: ucx" "$UCX_INFO_FILE" || {
    echo "ERROR: OpenMPI UCX PML unavailable"
    exit 14
}

clean_beegfs_paths() {
    local value="${1:-}"
    [[ -n "$value" ]] || return 0
    printf '%s\n' "$value" | tr ':' '\n' |
        awk '/^\/beegfs\/Tools\// {if (!seen[$0]++) print $0}' |
        paste -sd ':' -
}

CLEAN_PATH="$(clean_beegfs_paths "${PATH:-}")"
CLEAN_LD_LIBRARY_PATH="$(clean_beegfs_paths "${LD_LIBRARY_PATH:-}")"
CLEAN_LIBRARY_PATH="$(clean_beegfs_paths "${LIBRARY_PATH:-}")"
CLEAN_PKG_CONFIG_PATH="$(clean_beegfs_paths "${PKG_CONFIG_PATH:-}")"
CLEAN_CMAKE_PREFIX_PATH="$(clean_beegfs_paths "${CMAKE_PREFIX_PATH:-}")"

{
    echo '#!/bin/bash'
    echo '# Generated by fds_build.sh. /beegfs/Tools must be bound.'
    printf 'export MPI_HOME=%q\n' "$MPI_HOME"

    if [[ -n "$CLEAN_PATH" ]]; then
        printf 'export PATH=%q:${PATH:-/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin}\n' "$CLEAN_PATH"
    else
        echo 'export PATH="${MPI_HOME}/bin:${PATH:-/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin}"'
    fi

    if [[ -n "$CLEAN_LD_LIBRARY_PATH" ]]; then
        printf 'export LD_LIBRARY_PATH=%q:${LD_LIBRARY_PATH:-}\n' "$CLEAN_LD_LIBRARY_PATH"
    else
        echo 'export LD_LIBRARY_PATH="${MPI_HOME}/lib:${LD_LIBRARY_PATH:-}"'
    fi

    [[ -n "$CLEAN_LIBRARY_PATH" ]] && printf 'export LIBRARY_PATH=%q:${LIBRARY_PATH:-}\n' "$CLEAN_LIBRARY_PATH"
    [[ -n "$CLEAN_PKG_CONFIG_PATH" ]] && printf 'export PKG_CONFIG_PATH=%q:${PKG_CONFIG_PATH:-}\n' "$CLEAN_PKG_CONFIG_PATH"
    [[ -n "$CLEAN_CMAKE_PREFIX_PATH" ]] && printf 'export CMAKE_PREFIX_PATH=%q:${CMAKE_PREFIX_PATH:-}\n' "$CLEAN_CMAKE_PREFIX_PATH"

    echo 'unset CPATH'
    echo 'unset C_INCLUDE_PATH'
    echo 'unset CPLUS_INCLUDE_PATH'
} >"$ENV_FILE"

chmod 644 "$ENV_FILE"
test -s "$ENV_FILE" || { echo "ERROR: empty $ENV_FILE"; exit 15; }
bash -n "$ENV_FILE" || { echo "ERROR: invalid $ENV_FILE"; exit 16; }
grep -q 'OpenMPI/4.1.5-GCC-12.3.0' "$ENV_FILE" || {
    echo "ERROR: OpenMPI path missing from $ENV_FILE"
    exit 17
}

cat "$ENV_FILE"
rm -f "$IMAGE" "$BUILD_LOG" "$ERROR_LOG"

set +e
apptainer build \
    --force \
    --bind /beegfs/Tools:/beegfs/Tools:ro \
    --bind "${BASE_DIR}:${BASE_DIR}" \
    "$IMAGE" \
    "$DEF_FILE"
BUILD_RC=$?
set -e

if [[ "$BUILD_RC" -ne 0 ]]; then
    echo "ERROR: Apptainer build failed with $BUILD_RC"
    [[ -f "$ERROR_LOG" ]] && cat "$ERROR_LOG" || true
    [[ -f "$BUILD_LOG" ]] && tail -n 500 "$BUILD_LOG" || true
    exit "$BUILD_RC"
fi

test -s "$IMAGE" || { echo "ERROR: image missing or empty"; exit 30; }
ls -lh "$IMAGE"

set +e
apptainer exec \
    --cleanenv \
    --bind /beegfs/Tools:/beegfs/Tools:ro \
    "$IMAGE" \
    /bin/bash -lc '
        set -e
        set -o pipefail

        . /opt/host_mpi_env.sh
        unset CPATH C_INCLUDE_PATH CPLUS_INCLUDE_PATH

        export FDS_HOME=/opt/fds
        export FDS_BIN=/opt/fds/bin/fds
        export PATH=/opt/fds/bin:${PATH:-/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin}
        export OMP_NUM_THREADS=1

        gcc -dumpfullversion | grep -q "^12[.]3[.]0" || exit 1
        mpirun --version | sed -n "1p" | grep -q "4.1.5" || exit 2

        ompi_info --param pml ucx --level 1 >/tmp/container_ucx.txt 2>&1 || true
        cat /tmp/container_ucx.txt
        grep -q "MCA pml: ucx" /tmp/container_ucx.txt || exit 3

        test -x "$FDS_BIN" || exit 4
        file "$FDS_BIN"
        ldd "$FDS_BIN"

        if ldd "$FDS_BIN" | grep -q "not found"; then
            echo "ERROR: unresolved FDS libraries"
            exit 5
        fi

        MPI_LDD_LINE="$(ldd "$FDS_BIN" | grep -m1 -E "libmpi")"
        test -n "$MPI_LDD_LINE" || exit 6
        echo "$MPI_LDD_LINE"

        case "$MPI_LDD_LINE" in
            *"/beegfs/Tools/"*"OpenMPI/4.1.5-GCC-12.3.0/"*) ;;
            *) echo "ERROR: unexpected MPI library"; exit 7 ;;
        esac

        cat /opt/fds/FDS_GIT_COMMIT.txt
        "$FDS_BIN" -v || true
        echo "Container verification completed successfully"
    '
VERIFY_RC=$?
set -e

if [[ "$VERIFY_RC" -ne 0 ]]; then
    echo "ERROR: container verification failed with $VERIFY_RC"
    exit "$VERIFY_RC"
fi

echo "============================================================"
echo "FDS CONTAINER BUILD COMPLETED SUCCESSFULLY"
echo "============================================================"
echo "Image: $IMAGE"
echo "Build log: $BUILD_LOG"
echo "Required runtime bind: --bind /beegfs/Tools:/beegfs/Tools:ro"
